# Site settings
title: Not Just Pretty Pictures -- product design is more than how it looks
email: tony@notjustprettypictures.com
description: > # this means to ignore newlines until "baseurl:"
  The personal portfolio and blog of Tony Santos, digital designer extraodinaire. 
baseurl: "/~ts/tonysantosdotdesign/v5.0/" # the subpath of your site, e.g. /blog/
url: "http://www.tonysantos.design" # the base hostname & protocol for your site
twitter_username: tsmuse
github_username:  tsmuse

# Build settings
markdown: kramdown
destination: ~/Sites/tonysantosdotdesign/v5.0/
encoding: utf-8
exclude: [node_modules, Gruntfile.js, njpp5.sublime-project, njpp5.sublime-workspace, package.json, README.md, sass, workingFiles]
