# Site settings
title: Not Just Pretty Pictures -- product design is more than how it looks
email: tony@notjustprettypictures.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/~ts/njpp/v5.0/" # the subpath of your site, e.g. /blog/
url: "http://www.notjustprettypictures.com" # the base hostname & protocol for your site
twitter_username: tsmuse
github_username:  tsmuse

# Build settings
markdown: kramdown
destination: ~/Sites/njpp/v5.0/
encoding: utf-8
exclude: [node_modules, Gruntfile.js, njpp5.sublime-project, njpp5.sublime-workspace, package.json, README.md]
